### PR TITLE
Update example configuration to match each rule to each extension

### LINKED ISSUE #168: Enable the appropriate recommended config according to the extension
I read the code but didn't get it.

If I use the recommended configuration for `.json`, `.jsonc` and `.json5` at the same time, will it automatically use the appropriate configuration based on the file extension?

If not, what do I have to do to get them to use the appropriate configuration based on the extension.

### PR DESCRIPTION
**Pull request by politician**
Fixes #168

### CODE REVIEW

**Comment by ota-meshi** [comment]
Could you add a new example configuration for each extension, without changing the existing example?

**Comment by ota-meshi** [comment]
Or I think it makes sense to add it to the FAQ.
https://github.com/ota-meshi/eslint-plugin-jsonc/tree/master/docs/user-guide#question-faq

I prefer the first configuration example to be the simplest.

**Comment by politician** [comment]
> Could you add a new example configuration for each extension, without changing the existing example?

Unless I missed something, the current example is broken because it will parse json,json5,jsonc as jsonc.

The example I added is the only one I can think of that is not broken.

**Comment by ota-meshi** [comment]
I think there are many projects where you can use JSONC or JSON5 with the `.json` extension. For example, `tscondig.json` is JSONC.
In other words, it is up to the user to decide the format for each extension. Users can configure it to suit them.

If you think the existing configuration example is broken, the new configuration example is also broken for some users.

**Review by ota-meshi — CHANGES_REQUESTED** [review]
Mark it as `Request changes` to clarify the status of this PR.

**Comment by politician** [comment]
@ota-meshi I'm not up to date on the latest file extension standards vs accepted common usage, but surely these are exceptions rather than the norm? Such exception should be in the overrides and not the opposite.

I'll leave it up to you how you want to play it since you're the maintainer and more up to date than me on what is standard in the JS world. Please consider my PR as a suggestion and edit it (you are allowed) or close it as you see fit. 🙏

**Comment by ota-meshi** [comment]
I'm actually applying the current configuration example (recommended-with-jsonc) to `.json`, `.json5`.
(I prefer to unify .json5 to JSONC format, and it can be fixed immediately because it can be auto-fixed.)
(I've never used the `.jsonc` extension. Some users have used the `.jsonc`, so plugins are now supported as well.)

Also, the configuration provided by the plugin is documented, and the ESLint documentation describes how to change the configuration for each glob pattern. So I think there is already documentation on how to do that.

So I close this PR.

**Pull request closed without merging**
